"""
Strictly Out-of-Sample Fresh Universe for Klint-32M v2 Stress-Testing and Evaluation.

Guarantees 100% zero overlap with the 101 institutional assets used during pre-training
and fine-tuning (INSTITUTIONAL_100_TICKERS). Over 325 completely fresh assets across
6 major global asset classes.
"""

from typing import List, Dict

# The 101 training & fine-tuning tickers to strictly avoid (zero overlap guarantee)
TRAINING_EXCLUSION_TICKERS = {
    # 40 Equities
    "AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "TSLA", "AVGO",
    "AMD", "QCOM", "INTC", "CRM", "ORCL", "ADBE", "PLTR", "CSCO",
    "JPM", "V", "MA", "BAC", "WFC", "MS", "GS", "BLK", "COIN",
    "LLY", "UNH", "JNJ", "ABBV", "MRK", "PFE",
    "HD", "COST", "WMT", "PG", "KO",
    "CAT", "GE", "XOM", "CVX",
    # 20 ETFs
    "SPY", "QQQ", "IWM", "DIA", "VOO", "VTI",
    "XLK", "XLF", "XLV", "XLE", "XLI", "XLY", "XLP", "XLU", "XLB",
    "SMH", "SOXX", "ARKK", "EEM", "INDA",
    # 15 Crypto
    "BTC-USD", "ETH-USD", "SOL-USD", "BNB-USD", "XRP-USD",
    "ADA-USD", "DOGE-USD", "AVAX-USD", "LINK-USD", "DOT-USD",
    "NEAR-USD", "ATOM-USD", "LTC-USD", "BCH-USD", "XLM-USD",
    # 10 Commodities
    "GLD", "SLV", "USO", "UNG", "DBC", "CPER", "PPLT", "WEAT", "CORN", "SOYB",
    # 10 Rates
    "TLT", "IEF", "SHY", "BND", "AGG", "LQD", "HYG", "JNK", "TIP", "BIL",
    # 5 FX
    "EURUSD=X", "GBPUSD=X", "USDJPY=X", "AUDUSD=X", "USDCAD=X",
    # Tick Solana baseline
    "SOL",
}

# 325+ Curated Fresh Unseen Assets
FRESH_ASSETS_BY_CLASS: Dict[str, List[Dict[str, str]]] = {
    "Equities": [
        # Tech & Enterprise Software
        {"ticker": "NOW", "name": "ServiceNow Inc."},
        {"ticker": "INTU", "name": "Intuit Inc."},
        {"ticker": "IBM", "name": "IBM Corp."},
        {"ticker": "PANW", "name": "Palo Alto Networks"},
        {"ticker": "CRWD", "name": "CrowdStrike Holdings"},
        {"ticker": "FTNT", "name": "Fortinet Inc."},
        {"ticker": "ANET", "name": "Arista Networks"},
        {"ticker": "SNOW", "name": "Snowflake Inc."},
        {"ticker": "WDAY", "name": "Workday Inc."},
        {"ticker": "TEAM", "name": "Atlassian Corp."},
        {"ticker": "DDOG", "name": "Datadog Inc."},
        {"ticker": "NET", "name": "Cloudflare Inc."},
        {"ticker": "ZS", "name": "Zscaler Inc."},
        {"ticker": "TXN", "name": "Texas Instruments"},
        {"ticker": "MU", "name": "Micron Technology"},
        {"ticker": "AMAT", "name": "Applied Materials"},
        {"ticker": "LRCX", "name": "Lam Research"},
        {"ticker": "ADI", "name": "Analog Devices"},
        {"ticker": "KLAC", "name": "KLA Corp."},
        {"ticker": "SNPS", "name": "Synopsys Inc."},
        {"ticker": "CDNS", "name": "Cadence Design Systems"},
        {"ticker": "MCHP", "name": "Microchip Technology"},
        {"ticker": "NXPI", "name": "NXP Semiconductors"},
        {"ticker": "MRVL", "name": "Marvell Technology"},
        {"ticker": "ON", "name": "ON Semiconductor"},
        {"ticker": "MPWR", "name": "Monolithic Power Systems"},
        {"ticker": "TER", "name": "Teradyne Inc."},
        {"ticker": "KEYS", "name": "Keysight Technologies"},
        {"ticker": "TYL", "name": "Tyler Technologies"},
        {"ticker": "PATH", "name": "UiPath Inc."},
        {"ticker": "ESTC", "name": "Elastic N.V."},
        {"ticker": "GTLB", "name": "GitLab Inc."},
        {"ticker": "DOCU", "name": "DocuSign Inc."},
        {"ticker": "TWLO", "name": "Twilio Inc."},
        {"ticker": "OKTA", "name": "Okta Inc."},
        {"ticker": "ZM", "name": "Zoom Video Communications"},
        {"ticker": "MDB", "name": "MongoDB Inc."},
        {"ticker": "CFLT", "name": "Confluent Inc."},
        {"ticker": "BILL", "name": "BILL Holdings"},
        {"ticker": "IOT", "name": "Samsara Inc."},
        # Financials & Asset Managers
        {"ticker": "AXP", "name": "American Express Co."},
        {"ticker": "SCHW", "name": "Charles Schwab Corp."},
        {"ticker": "SPGI", "name": "S&P Global Inc."},
        {"ticker": "MCO", "name": "Moody's Corp."},
        {"ticker": "PNC", "name": "PNC Financial Services"},
        {"ticker": "USB", "name": "U.S. Bancorp"},
        {"ticker": "TFC", "name": "Truist Financial Corp."},
        {"ticker": "BK", "name": "Bank of New York Mellon"},
        {"ticker": "CME", "name": "CME Group Inc."},
        {"ticker": "ICE", "name": "Intercontinental Exchange"},
        {"ticker": "AIG", "name": "American International Group"},
        {"ticker": "ALL", "name": "Allstate Corp."},
        {"ticker": "TRV", "name": "Travelers Companies"},
        {"ticker": "PRU", "name": "Prudential Financial"},
        {"ticker": "MET", "name": "MetLife Inc."},
        {"ticker": "AMP", "name": "Ameriprise Financial"},
        {"ticker": "HIG", "name": "Hartford Financial Services"},
        {"ticker": "MTB", "name": "M&T Bank Corp."},
        {"ticker": "FITB", "name": "Fifth Third Bancorp"},
        {"ticker": "KEY", "name": "KeyCorp"},
        {"ticker": "HBAN", "name": "Huntington Bancshares"},
        {"ticker": "RF", "name": "Regions Financial Corp."},
        {"ticker": "CFG", "name": "Citizens Financial Group"},
        {"ticker": "CINF", "name": "Cincinnati Financial"},
        {"ticker": "BRO", "name": "Brown & Brown Inc."},
        {"ticker": "WRB", "name": "W.R. Berkley Corp."},
        {"ticker": "RJF", "name": "Raymond James Financial"},
        {"ticker": "NTRS", "name": "Northern Trust Corp."},
        {"ticker": "STT", "name": "State Street Corp."},
        {"ticker": "DFS", "name": "Discover Financial Services"},
        # Healthcare & Life Sciences
        {"ticker": "TMO", "name": "Thermo Fisher Scientific"},
        {"ticker": "ABT", "name": "Abbott Laboratories"},
        {"ticker": "DHR", "name": "Danaher Corp."},
        {"ticker": "AMGN", "name": "Amgen Inc."},
        {"ticker": "ISRG", "name": "Intuitive Surgical Inc."},
        {"ticker": "VRTX", "name": "Vertex Pharmaceuticals"},
        {"ticker": "REGN", "name": "Regeneron Pharmaceuticals"},
        {"ticker": "MDT", "name": "Medtronic plc"},
        {"ticker": "BMY", "name": "Bristol-Myers Squibb"},
        {"ticker": "GILD", "name": "Gilead Sciences"},
        {"ticker": "SYK", "name": "Stryker Corp."},
        {"ticker": "BSX", "name": "Boston Scientific"},
        {"ticker": "CVS", "name": "CVS Health Corp."},
        {"ticker": "ELV", "name": "Elevance Health Inc."},
        {"ticker": "CI", "name": "The Cigna Group"},
        {"ticker": "HUM", "name": "Humana Inc."},
        {"ticker": "BDX", "name": "Becton Dickinson"},
        {"ticker": "EW", "name": "Edwards Lifesciences"},
        {"ticker": "ZTS", "name": "Zoetis Inc."},
        {"ticker": "IDXX", "name": "IDEXX Laboratories"},
        {"ticker": "IQV", "name": "IQVIA Holdings"},
        {"ticker": "RMD", "name": "ResMed Inc."},
        {"ticker": "DXCM", "name": "DexCom Inc."},
        {"ticker": "A", "name": "Agilent Technologies"},
        {"ticker": "MTD", "name": "Mettler-Toledo International"},
        {"ticker": "WST", "name": "West Pharmaceutical Services"},
        {"ticker": "WAT", "name": "Waters Corp."},
        {"ticker": "HOLX", "name": "Hologic Inc."},
        {"ticker": "ALGN", "name": "Align Technology"},
        {"ticker": "BIIB", "name": "Biogen Inc."},
        {"ticker": "MRNA", "name": "Moderna Inc."},
        {"ticker": "VTRS", "name": "Viatris Inc."},
        {"ticker": "INCY", "name": "Incyte Corp."},
        {"ticker": "PODD", "name": "Insulet Corp."},
        {"ticker": "TECH", "name": "Bio-Techne Corp."},
        # Consumer Staples & Discretionary
        {"ticker": "PEP", "name": "PepsiCo Inc."},
        {"ticker": "MCD", "name": "McDonald's Corp."},
        {"ticker": "NKE", "name": "NIKE Inc."},
        {"ticker": "SBUX", "name": "Starbucks Corp."},
        {"ticker": "TGT", "name": "Target Corp."},
        {"ticker": "LOW", "name": "Lowe's Companies"},
        {"ticker": "TJX", "name": "The TJX Companies"},
        {"ticker": "BKNG", "name": "Booking Holdings"},
        {"ticker": "ABNB", "name": "Airbnb Inc."},
        {"ticker": "UBER", "name": "Uber Technologies"},
        {"ticker": "MDLZ", "name": "Mondelez International"},
        {"ticker": "PM", "name": "Philip Morris International"},
        {"ticker": "MO", "name": "Altria Group"},
        {"ticker": "CL", "name": "Colgate-Palmolive Co."},
        {"ticker": "KMB", "name": "Kimberly-Clark Corp."},
        {"ticker": "GIS", "name": "General Mills Inc."},
        {"ticker": "HSY", "name": "The Hershey Company"},
        {"ticker": "K", "name": "Kellanova"},
        {"ticker": "MNST", "name": "Monster Beverage Corp."},
        {"ticker": "STZ", "name": "Constellation Brands"},
        {"ticker": "KDP", "name": "Keurig Dr Pepper"},
        {"ticker": "SYY", "name": "Sysco Corp."},
        {"ticker": "ADM", "name": "Archer-Daniels-Midland"},
        {"ticker": "TSN", "name": "Tyson Foods"},
        {"ticker": "EL", "name": "The Estee Lauder Companies"},
        {"ticker": "LULU", "name": "Lululemon Athletica"},
        {"ticker": "ROST", "name": "Ross Stores Inc."},
        {"ticker": "ORLY", "name": "O'Reilly Automotive"},
        {"ticker": "AZO", "name": "AutoZone Inc."},
        {"ticker": "EBAY", "name": "eBay Inc."},
        {"ticker": "ETSY", "name": "Etsy Inc."},
        {"ticker": "DHI", "name": "D.R. Horton Inc."},
        {"ticker": "LEN", "name": "Lennar Corp."},
        {"ticker": "PHM", "name": "PulteGroup Inc."},
        {"ticker": "NVR", "name": "NVR Inc."},
        # Energy, Industrials & Materials
        {"ticker": "COP", "name": "ConocoPhillips"},
        {"ticker": "SLB", "name": "Schlumberger Ltd."},
        {"ticker": "EOG", "name": "EOG Resources"},
        {"ticker": "MPC", "name": "Marathon Petroleum"},
        {"ticker": "PSX", "name": "Phillips 66"},
        {"ticker": "VLO", "name": "Valero Energy"},
        {"ticker": "OXY", "name": "Occidental Petroleum"},
        {"ticker": "KMI", "name": "Kinder Morgan"},
        {"ticker": "WMB", "name": "Williams Companies"},
        {"ticker": "HAL", "name": "Halliburton Co."},
        {"ticker": "BKR", "name": "Baker Hughes Co."},
        {"ticker": "FANG", "name": "Diamondback Energy"},
        {"ticker": "DVN", "name": "Devon Energy"},
        {"ticker": "HES", "name": "Hess Corp."},
        {"ticker": "MRO", "name": "Marathon Oil"},
        {"ticker": "DE", "name": "Deere & Co."},
        {"ticker": "HON", "name": "Honeywell International"},
        {"ticker": "UNP", "name": "Union Pacific Corp."},
        {"ticker": "UPS", "name": "United Parcel Service"},
        {"ticker": "FDX", "name": "FedEx Corp."},
        {"ticker": "BA", "name": "The Boeing Co."},
        {"ticker": "LMT", "name": "Lockheed Martin"},
        {"ticker": "RTX", "name": "RTX Corp."},
        {"ticker": "NOC", "name": "Northrop Grumman"},
        {"ticker": "GD", "name": "General Dynamics"},
        {"ticker": "ETN", "name": "Eaton Corp."},
        {"ticker": "ITW", "name": "Illinois Tool Works"},
        {"ticker": "EMR", "name": "Emerson Electric"},
        {"ticker": "PH", "name": "Parker-Hannifin Corp."},
        {"ticker": "CSX", "name": "CSX Corp."},
    ],
    "ETFs": [
        {"ticker": "IVV", "name": "iShares Core S&P 500 ETF"},
        {"ticker": "IWF", "name": "iShares Russell 1000 Growth ETF"},
        {"ticker": "IWD", "name": "iShares Russell 1000 Value ETF"},
        {"ticker": "MDY", "name": "SPDR S&P MidCap 400 ETF"},
        {"ticker": "RSP", "name": "Invesco S&P 500 Equal Weight"},
        {"ticker": "XLRE", "name": "Real Estate Select Sector SPDR"},
        {"ticker": "XLC", "name": "Communication Services Select Sector"},
        {"ticker": "XBI", "name": "SPDR S&P Biotech ETF"},
        {"ticker": "IBB", "name": "iShares Biotechnology ETF"},
        {"ticker": "KRE", "name": "SPDR S&P Regional Banking ETF"},
        {"ticker": "XHB", "name": "SPDR S&P Homebuilders ETF"},
        {"ticker": "XRT", "name": "SPDR S&P Retail ETF"},
        {"ticker": "XME", "name": "SPDR S&P Metals & Mining ETF"},
        {"ticker": "OIH", "name": "VanEck Oil Services ETF"},
        {"ticker": "JETS", "name": "U.S. Global Jets ETF"},
        {"ticker": "ARKG", "name": "ARK Genomic Revolution ETF"},
        {"ticker": "ARKW", "name": "ARK Next Generation Internet ETF"},
        {"ticker": "TAN", "name": "Invesco Solar ETF"},
        {"ticker": "ICLN", "name": "iShares Global Clean Energy ETF"},
        {"ticker": "EFA", "name": "iShares MSCI EAFE ETF"},
        {"ticker": "VWO", "name": "Vanguard FTSE Emerging Markets"},
        {"ticker": "VEA", "name": "Vanguard FTSE Developed Markets"},
        {"ticker": "FXI", "name": "iShares China Large-Cap ETF"},
        {"ticker": "KWEB", "name": "KraneShares CSI China Internet ETF"},
        {"ticker": "EWJ", "name": "iShares MSCI Japan ETF"},
        {"ticker": "EWG", "name": "iShares MSCI Germany ETF"},
        {"ticker": "EWU", "name": "iShares MSCI United Kingdom ETF"},
        {"ticker": "EWY", "name": "iShares MSCI South Korea ETF"},
        {"ticker": "EWZ", "name": "iShares MSCI Brazil ETF"},
        {"ticker": "EWT", "name": "iShares MSCI Taiwan ETF"},
        {"ticker": "IGV", "name": "iShares Expanded Tech-Software"},
        {"ticker": "ITA", "name": "iShares U.S. Aerospace & Defense"},
        {"ticker": "XOP", "name": "SPDR S&P Oil & Gas Exploration"},
        {"ticker": "VNQ", "name": "Vanguard Real Estate ETF"},
        {"ticker": "SCHH", "name": "Schwab U.S. REIT ETF"},
        {"ticker": "IYR", "name": "iShares U.S. Real Estate ETF"},
        {"ticker": "IYT", "name": "iShares Transportation Average ETF"},
        {"ticker": "VHT", "name": "Vanguard Health Care ETF"},
        {"ticker": "VGT", "name": "Vanguard Information Technology"},
        {"ticker": "VCR", "name": "Vanguard Consumer Discretionary"},
        {"ticker": "VDC", "name": "Vanguard Consumer Staples"},
        {"ticker": "VIS", "name": "Vanguard Industrials ETF"},
        {"ticker": "VAW", "name": "Vanguard Materials ETF"},
        {"ticker": "VOX", "name": "Vanguard Communication Services"},
        {"ticker": "VPU", "name": "Vanguard Utilities ETF"},
        {"ticker": "QUAL", "name": "iShares MSCI USA Quality Factor"},
        {"ticker": "USMV", "name": "iShares MSCI USA Min Vol Factor"},
        {"ticker": "MTUM", "name": "iShares MSCI USA Momentum Factor"},
        {"ticker": "VLUE", "name": "iShares MSCI USA Value Factor"},
        {"ticker": "DVY", "name": "iShares Select Dividend ETF"},
        {"ticker": "SDY", "name": "SPDR S&P Dividend ETF"},
        {"ticker": "VYM", "name": "Vanguard High Dividend Yield"},
        {"ticker": "SCHD", "name": "Schwab U.S. Dividend Equity"},
        {"ticker": "COMT", "name": "iShares Commodity Select Strategy"},
        {"ticker": "USCI", "name": "United States Commodity Index Fund"},
    ],
    "Crypto": [
        {"ticker": "SUI-USD", "name": "Sui USD"},
        {"ticker": "APT-USD", "name": "Aptos USD"},
        {"ticker": "TRX-USD", "name": "TRON USD"},
        {"ticker": "TON11419-USD", "name": "Toncoin USD"},
        {"ticker": "ALGO-USD", "name": "Algorand USD"},
        {"ticker": "FTM-USD", "name": "Fantom USD"},
        {"ticker": "HBAR-USD", "name": "Hedera USD"},
        {"ticker": "ICP-USD", "name": "Internet Computer USD"},
        {"ticker": "KAS-USD", "name": "Kaspa USD"},
        {"ticker": "SEI-USD", "name": "Sei USD"},
        {"ticker": "TIA-USD", "name": "Celestia USD"},
        {"ticker": "INJ-USD", "name": "Injective USD"},
        {"ticker": "MATIC-USD", "name": "Polygon USD"},
        {"ticker": "OP-USD", "name": "Optimism USD"},
        {"ticker": "ARB-USD", "name": "Arbitrum USD"},
        {"ticker": "STX-USD", "name": "Stacks USD"},
        {"ticker": "IMX-USD", "name": "Immutable USD"},
        {"ticker": "MANTA-USD", "name": "Manta Network USD"},
        {"ticker": "UNI-USD", "name": "Uniswap USD"},
        {"ticker": "AAVE-USD", "name": "Aave USD"},
        {"ticker": "MKR-USD", "name": "Maker USD"},
        {"ticker": "SNX-USD", "name": "Synthetix USD"},
        {"ticker": "RUNE-USD", "name": "THORChain USD"},
        {"ticker": "CRV-USD", "name": "Curve DAO USD"},
        {"ticker": "LDO-USD", "name": "Lido DAO USD"},
        {"ticker": "PENDLE-USD", "name": "Pendle USD"},
        {"ticker": "PYTH-USD", "name": "Pyth Network USD"},
        {"ticker": "JUP-USD", "name": "Jupiter USD"},
        {"ticker": "RBN-USD", "name": "Ribbon Finance USD"},
        {"ticker": "DYDX-USD", "name": "dYdX USD"},
        {"ticker": "ETC-USD", "name": "Ethereum Classic USD"},
        {"ticker": "SHIB-USD", "name": "Shiba Inu USD"},
        {"ticker": "PEPE24478-USD", "name": "Pepe USD"},
        {"ticker": "WIF-USD", "name": "dogwifhat USD"},
        {"ticker": "BONK-USD", "name": "Bonk USD"},
        {"ticker": "FLOKI-USD", "name": "FLOKI USD"},
        {"ticker": "GRT-USD", "name": "The Graph USD"},
        {"ticker": "RNDR-USD", "name": "Render USD"},
        {"ticker": "THETA-USD", "name": "Theta Network USD"},
        {"ticker": "EGLD-USD", "name": "MultiversX USD"},
        {"ticker": "SAND-USD", "name": "The Sandbox USD"},
        {"ticker": "MANA-USD", "name": "Decentraland USD"},
        {"ticker": "AXS-USD", "name": "Axie Infinity USD"},
        {"ticker": "GALA-USD", "name": "GALA USD"},
        {"ticker": "FLOW-USD", "name": "Flow USD"},
    ],
    "Commodities": [
        {"ticker": "IAU", "name": "iShares Gold Trust"},
        {"ticker": "PALL", "name": "abrdn Physical Palladium"},
        {"ticker": "SGOL", "name": "abrdn Physical Gold Shares"},
        {"ticker": "DBB", "name": "Invesco DB Base Metals Fund"},
        {"ticker": "BNO", "name": "United States Brent Oil Fund"},
        {"ticker": "UGA", "name": "United States Gasoline Fund"},
        {"ticker": "DBE", "name": "Invesco DB Energy Fund"},
        {"ticker": "DBA", "name": "Invesco DB Agriculture Fund"},
        {"ticker": "CANE", "name": "Teucrium Sugar Fund"},
        {"ticker": "COW", "name": "iPath Bloomberg Livestock"},
        {"ticker": "GSG", "name": "iShares S&P GSCI Commodity"},
        {"ticker": "PDBC", "name": "Invesco Optimum Yield Diversified"},
        {"ticker": "COMB", "name": "GraniteShares Bloomberg Commodity"},
        {"ticker": "BCI", "name": "abrdn Bloomberg All Commodity"},
        {"ticker": "FTGC", "name": "First Trust Tactical Commodity"},
        {"ticker": "GCC", "name": "WisdomTree Commodity Strategy"},
        {"ticker": "CMDY", "name": "iShares Roll Select Commodity"},
        {"ticker": "GLTR", "name": "abrdn Physical Precious Metals"},
        {"ticker": "SLVP", "name": "iShares MSCI Global Silver Miners"},
        {"ticker": "GDX", "name": "VanEck Gold Miners ETF"},
    ],
    "Fixed_Income": [
        {"ticker": "IEI", "name": "iShares 3-7 Year Treasury Bond"},
        {"ticker": "SGOV", "name": "iShares 0-3 Month Treasury Bond"},
        {"ticker": "GOVT", "name": "iShares U.S. Treasury Bond"},
        {"ticker": "VCIT", "name": "Vanguard Intermediate-Term Corporate"},
        {"ticker": "VCSH", "name": "Vanguard Short-Term Corporate"},
        {"ticker": "SHYG", "name": "iShares 0-5 Year High Yield Corporate"},
        {"ticker": "BNDX", "name": "Vanguard Total International Bond"},
        {"ticker": "MUB", "name": "iShares National Muni Bond"},
        {"ticker": "EMB", "name": "iShares J.P. Morgan USD Emerging Markets"},
        {"ticker": "PCY", "name": "Invesco Emerging Markets Sovereign"},
        {"ticker": "IGSB", "name": "iShares 1-5 Year Investment Grade"},
        {"ticker": "IGIB", "name": "iShares 5-10 Year Investment Grade"},
        {"ticker": "USHY", "name": "iShares Broad USD High Yield Bond"},
        {"ticker": "ANGL", "name": "VanEck Fallen Angel High Yield Bond"},
        {"ticker": "BKLN", "name": "Invesco Senior Loan ETF"},
        {"ticker": "FLOT", "name": "iShares Floating Rate Bond ETF"},
        {"ticker": "SRLN", "name": "SPDR Blackstone Senior Loan ETF"},
        {"ticker": "STIP", "name": "iShares 0-5 Year TIPS Bond ETF"},
        {"ticker": "VTIP", "name": "Vanguard Short-Term Inflation-Protected"},
        {"ticker": "FMB", "name": "First Trust Managed Municipal ETF"},
    ],
    "FX": [
        {"ticker": "USDCHF=X", "name": "USD/CHF US Dollar to Swiss Franc"},
        {"ticker": "NZDUSD=X", "name": "NZD/USD New Zealand Dollar to US Dollar"},
        {"ticker": "EURGBP=X", "name": "EUR/GBP Euro to British Pound"},
        {"ticker": "EURJPY=X", "name": "EUR/JPY Euro to Japanese Yen"},
        {"ticker": "GBPJPY=X", "name": "GBP/JPY British Pound to Japanese Yen"},
        {"ticker": "EURCHF=X", "name": "EUR/CHF Euro to Swiss Franc"},
        {"ticker": "AUDJPY=X", "name": "AUD/JPY Australian Dollar to Japanese Yen"},
        {"ticker": "CADJPY=X", "name": "CAD/JPY Canadian Dollar to Japanese Yen"},
        {"ticker": "USDCNH=X", "name": "USD/CNH US Dollar to Chinese Yuan"},
        {"ticker": "USDINR=X", "name": "USD/INR US Dollar to Indian Rupee"},
        {"ticker": "USDMXN=X", "name": "USD/MXN US Dollar to Mexican Peso"},
        {"ticker": "USDZAR=X", "name": "USD/ZAR US Dollar to South African Rand"},
        {"ticker": "USDBRL=X", "name": "USD/BRL US Dollar to Brazilian Real"},
        {"ticker": "USDSGD=X", "name": "USD/SGD US Dollar to Singapore Dollar"},
        {"ticker": "USDHKD=X", "name": "USD/HKD US Dollar to Hong Kong Dollar"},
    ],
}


def get_fresh_300_universe(max_assets: int = 325) -> List[Dict[str, str]]:
    """
    Returns a verified list of fresh out-of-sample assets with strict
    assertion verifying ZERO intersection with training or fine-tuning tickers.
    """
    selected: List[Dict[str, str]] = []
    seen = set()

    for asset_class, assets in FRESH_ASSETS_BY_CLASS.items():
        for asset in assets:
            t = asset["ticker"]
            if t in seen:
                continue
            if t in TRAINING_EXCLUSION_TICKERS:
                raise ValueError(
                    f"CRITICAL DATA LEAKAGE: Ticker {t} belongs to the training set!"
                )
            selected.append({
                "ticker": t,
                "name": asset["name"],
                "asset_class": asset_class,
            })
            seen.add(t)
            if len(selected) >= max_assets:
                break
        if len(selected) >= max_assets:
            break

    # Verification: Assert zero overlap
    overlap = seen.intersection(TRAINING_EXCLUSION_TICKERS)
    assert len(overlap) == 0, f"DATA LEAK DETECTED: Overlap tickers: {overlap}"
    assert len(selected) >= 300, f"Expected >= 300 assets, got {len(selected)}"
    return selected


if __name__ == "__main__":
    universe = get_fresh_300_universe()
    print(f"Verified Fresh Out-of-Sample Universe: {len(universe)} assets")
    classes = {}
    for a in universe:
        classes[a["asset_class"]] = classes.get(a["asset_class"], 0) + 1
    for c, cnt in classes.items():
        print(f"  - {c}: {cnt} assets")
